version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ipv_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ipv_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../backend/app/utils/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ipv_user -d ipv_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://ipv_user:password@postgres:5432/ipv_db
      REDIS_URL: redis://redis:6379/0
      BREACH_THRESHOLD_PCT: "0.5"
      LOG_LEVEL: INFO
      FLASK_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../backend:/app

volumes:
  postgres_data:
